[project]
name = "managed-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Indivar Mishra", email = "indimishra@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
managed-mcp = "managed_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
